### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by yortus** [sungwoncho/match-bracket#3]
Hi @sungwoncho,

I came across this on HN and took a look. I appreciate your effort in trying to solve a problem for people. I have a couple of suggestions for improvements:
1. Since your example is searching through JavaScript code, I suggest taking into account context changes in the JS code that will currently produce incorrect results:
   - **quoted strings** e.g. `if (str === ")") {...}`
   - **comments** e.g. `while (notFound /* loop until ) char found ) */) {...}`
2. The API is asynchronous but the source code performs no truly asynchronous operations (like disk accesses, timeouts, etc). This adds complexity but no benefits. The code would be more efficient, and the API simpler, if it just iterated over the characters in the provided string, using `string#charAt()` or array indexing on the string.

On point (1) above, tracking quoted strings is itself a little complex. There are three delimiter kinds (`'`, `"`, and `), and searching for the closing string delimiter is complicated by escape sequences like `"\"foo\""`. Also, strings might contain comments and vice-versa. You probably need to implement a state machine to handle all this reliably.

Good luck!

**Comment by yortus** [comment]
Also add **regexes** in the code to point (1) above.

**Comment by sungwoncho** [comment]
@yortus your suggestions help me learn a great deal.

**1. incorrect results**

I'm aware of some limitations. Thanks for illuminating them.

**2. Synchronous API**

That is a reasonable suggestion. I ditched the readable stream. Instead, I used indices on the string to loop through all characters. (PR #4) Now the code is less complex.

This got me wondering: in what situations is it best to implement async API? Is it when the code needs to perform operations that might take too long?

**Comment by yortus** [comment]
@sungwoncho regarding when to implement an asynchronous API, here are a couple of tips:
1. If the implementation itself must make asynchronous calls, eg reading a file, querying a database, etc, then the API **must** be asynchronous in order to return its result and/or indicate completion/errors. That is, async code is 'contageous'.
2. If the implementation is long-running but essentially synchronous (like your module here), then it is CPU-bound. Simply making it asynchronous won't help, because Node.js code all runs in a single thread and if the implementation never yields control, then nothing else can run anyway until your operation completes (this is called 'starvation'). You could mitigate this using the `cluster` module but that's not something a library would normally do. So generally I'd leave this kind of code with a synchronous API, but put a big warning in the README that it is CPU bound and that client code should use it accordingly, e.g. by using the `cluster` module, or just accepting that it blocks (which would be fine for a CLI application). **EDIT**: I suppose you could also break up the long-running operation into smaller units and schedule them with `setTimeout()` or `setInterval()` - then you would have an asynchronous API.

**Comment by yortus** [comment]
The `for` loop looks much simpler! Nice.

Regarding strings/comments/regexes in the code, may I suggest a challenge? When you get the correct results using your own source code as the input string, then you will have a good solid foundation.

**Comment by sungwoncho** [comment]
Just published v0.1.1. It smartly handles the cases of quoted strings and comments. There are still some edge cases but this is good for now. The API is now synchronous. Thanks @yortus .

**Comment by sungwoncho** [comment]
Published as v1.0.0 as there is a breaking API change.
